### PR TITLE
AutoPatch feature

### PR DESCRIPTION
**Pull request by LecrisUT**
Also did some cleaning on the gitignore.
Please run this on your end to update the gitignore.
Also Squash/Merge the commits before applying it.
```
git rm -r --cached ./
git add ./
```

### CODE REVIEW

**Comment by Jellypowered** [comment]
Was this meant to address the "hammer needed for hauling?" 

Everything seems to work flawlessly with your new auto patching implementation, however I'm still getting the notification for Hauling jobs.

**Comment by LecrisUT** [comment]
Yes, that's what it should address. Hmm can you give me an example?

PS: don't forget to recompile on your end. The dll is no longer included in developing commits. (To be included only in the release section)

**Comment by Jellypowered** [comment]
Limited testing on this end, I did compile thanks for the reminder though, that is something I would do haha. 

XND Turret Extensions gives a couple hauling tasks that trigger the "Colonist needs tools" alert. 
If I disable them manually in the work priorities the notification for needing a hauling tool goes away.

**Comment by LecrisUT** [comment]
I'll check again. I explicitly tested the turret expansion mod and it didn't get included. Send me the log just in case. It prints out the jobs it patches

**Comment by LecrisUT** [comment]
Oh, I know, do you still have the [old WorkGiver patch file](https://github.com/Jellypowered/SurvivalTools/blob/master/1.1/Patches/Core/WorkGiverDefs/WorkGivers.xml) in your session?

I have just reconfirmed the deliver work givers do not trigger missing tool.
Although I found I still need to fix the autopatch to include modded jobdefs.

**Pull request merged**
