### PR TITLE
Mod patches

### PR DESCRIPTION
**Pull request by LecrisUT**
RPG Style Level Up
and MiscRobots++

### CODE REVIEW

**Comment by LecrisUT** [comment]
I think we are almost ready for a release. The only remaining addition I think is the neolithic tools.

**Comment by Jellypowered** [comment]
https://gist.github.com/20910e429a635004c776f49cf6e7c498
getting some errors that weren't there before I merged this PR.

**Comment by LecrisUT** [comment]
Yeah it's my fault for reorganizing the name. Can you check that you have omly one `StatPatch.xml` or similar file? It should be deleted, except for the one in `1.1/Defs/Misc`.

I also see there's a translation error I don't recognise. Don't know how to check that.

**Comment by Jellypowered** [comment]
Deleting the Temp_Patch/StatPatch.xml fixed it lol.

**Pull request merged**
