### PR TITLE
Russian translate

### PR DESCRIPTION
**Pull request by Taranchuk**

### CODE REVIEW

**Comment by LecrisUT** [comment]
Thank you for the contribution. Just a note, code in general should have a new line at the end of the files. Not sure why, but I get some flack for that sometimes.

**Comment by LecrisUT** [comment]
@Taranchuk, btw there are new items introduced/being introduced. Is it ok to mention you when all the new items are fully introduced?

**Comment by Taranchuk** [comment]
This is not my translation, but I will try to add new keys

**Comment by Jellypowered** [comment]
Thanks Taranchuk! I've merged your PR. It will be live soon!

**Pull request merged**
